version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres:16-alpine
    hostname: localhost
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - datalayer:/var/lib/postgresql/data
      - ./_ca/server.crt:/var/lib/postgresql/server.crt:ro
      - ./_ca/server.key:/var/lib/postgresql/server.key:ro
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  datalayer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_datalayer
