name: Release CLI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build and Release CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build all CLI binaries
        run: make build_cli_all

      - name: Determine if prerelease
        id: prerelease_check
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          if [[ "$TAG_NAME" == *"+"* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ steps.prerelease_check.outputs.IS_PRERELEASE }}
          files: |
            build/orca-cli-linux
            build/orca-cli-windows.exe
            build/orca-cli-mac-arm
            build/orca-cli-mac-intel
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}}
