name: CD

on:
  pull_request:
    branches: ["release/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Test
        run: make test

      - name: Build CLI
        run: make build_cli_all

      - name: Build Core
        run: make build_core_all
