# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**/**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Test
        run: make test
